### ISSUE TITLE
a command or something like that to find out if the bridge is open or not

### ISSUE THREAD

**Issue by kleeder** [langel/vombot#12]
example: if youre on discord, theres an easy way to find out if your message was sent to irc. simply use a irc_bot-command (!help) and if you get a reply, you know the bridge is working.

but if youre on irc, theres no way (?) to check if everything works unless you go onto the discord server. the bad way of doing this would be to get a 3rd bot to discord which replies to something like "?check_connection". lol, the better way would be to use vombot obviously.

would be helpful, because most of the time, vom is still in the channel, posting random stuff, so it looks like it's working

**Comment by argarak** [comment]
for a simple boolean output it should be simple enough to define something `!conn` to a function which uses `bot.say` to output the value of `bot.connected` converted to string

**Comment by langel** [comment]
vombot no longer the irc<->discord bridge
