### ISSUE TITLE
markov async init

### ISSUE THREAD

**Issue by langel** [langel/vombot#14]
bot takes forever to boot because its processing the giant ass log file for markov

maybe bust out the markov lib into its module
make another repo and make it a dependency

but.... also.... as the title says:
process the markov data set asynchronously so it doesn't block initialization
could return some string in the meantime if called: "processing data . . ."
....or something

**Comment by tatey12** [comment]
Yes

**Comment by langel** [comment]
this has actually been resolved since i moved all markov functionality to its own microservice recently
