### ISSUE TITLE
Images do not cross over from discord

### ISSUE THREAD

**Issue by ghost** [langel/vombot#3]
.

**Comment by langel** [comment]
can you post examples of what it looks like on both ends?

**Comment by langel** [comment]
user uploads image to discord
discord displays image
but irc displays empty message

**Comment by kleeder** [comment]
getting the image-url out of the message is easy. the message has attachments > 0 if theres an image, you grab the image-url and post it instead of the text-string

**Comment by hypercda** [comment]
> can you post examples of what it looks like on both ends?

<img width="1046" alt="botb-vombot-needs-image-links-annotated" src="https://user-images.githubusercontent.com/3814665/81462517-004bd580-9181-11ea-936c-6c0943b98f35.png">

**Comment by langel** [comment]
attachment URLs now come across on the relay bridge
